### ISSUE TITLE
Chrome 54 android 6.0 手机上测试视频，无画面

### ISSUE THREAD

**Issue by dingyiming** [WildDogTeam/video-demo-web-conversation#1]
Chrome 54 android 6.1 手机上测试视频，无画面
![screenshot_2016-10-21-12-46-18-166_com android ch](https://cloud.githubusercontent.com/assets/12537013/19586934/b72390ec-978c-11e6-8747-6b932099c4e5.png)
![screenshot_2016-10-21-12-46-37-225_com android ch](https://cloud.githubusercontent.com/assets/12537013/19586935/b72b2cda-978c-11e6-9cb9-39812ce6d62b.png)

**Comment by itolfh** [comment]
好的，我们check一下

**Comment by dingyiming** [comment]
@itolfh 谢谢

**Comment by itolfh** [comment]
抱歉暂时没有找到android 6.1 的机器，不过我们在android 6.0 上的chrome 53中是可以看到画面的。
出现这种情况应该是浏览器获取摄像头失败，有可能是由于网页服务器不是 https 的。

**Comment by dingyiming** [comment]
@itolfh 哦，抱歉是我疏忽了，加了https的确在 chrome54 andorid6.0可用的，同时尝试了其他一些浏览器，发现 firefox 和opera是可用的，但国内其他常见浏览器，比如uc, 搜狗，猎豹，qq,百度，360都没有用，感谢

**Comment by itolfh** [comment]
是的，chrome firefox和opera对 webrtc 的支持是最标准的，国内一些浏览器有些不是chrome内核，有些是经过修改的，所以存在不支持的情况，我们后面也会增加对更多浏览器的支持。

**Comment by dingyiming** [comment]
@itolfh 非常感谢，建议在官方文档中添加web 移动端浏览器测试的列表，目前看文档中未提及测试情况，只是在控制台进入项目后有一点说明，

**Comment by itolfh** [comment]
好的，这个建议很好，谢谢。
